import Footer from "../../components/footer";
import Header from "../../components/header";
import Tab from "../../components/tab";
import React from "react";

const  discents = [ 
    {title:"Anderson Almeida Ferreira",image:"https://st2.depositphotos.com/4431055/11856/i/600/depositphotos_118565150-stock-photo-young-male-teacher.jpg",body:{role:"Doutor em Ciência da Computação - Universidade Federal de Minas Gerais", classroom:"Instituto de Ciências Exatas e Biológicas - Sala 340", email:"cfmcc@iceb.ufop.br", lattes:"http://lattes.cnpq.br/7884364909927473", areaInterest:"Teoria da Computação. Bibliotecas Digitais. Bancos de Dados. Gerência de Dados. Recuperação de Informação. Aprendizado de Máquina", tel:" "}}, 
    {title:"Andrea Gomes Campos Bianchi",image:"https://media.istockphoto.com/id/687830554/photo/portrait-of-a-happy-latin-american-teacher-at-the-school.jpg?b=1&s=170667a&w=0&k=20&c=uNKFMoebdWk1fMYsAQicTvDARuMVibx4pskppByrh5Q=",body:{role:"Doutora em Física Computacional - Universidade de São Paulo/São Carlos", classroom:"Instituto de Ciências Exatas e Biológicas - Sala 64", email:"andrea@iceb.ufop.br", lattes:"http://lattes.cnpq.br/0251364589832974", areaInterest:"Visão Computacional. Análise e processamento de imagens. Simulação computacional. Reconhecimento de padrões.", tel:"+55 (31) 3559 1640"}},
    {title:"Carlos Frederico M. C. Cavalcanti",image:"https://st2.depositphotos.com/4431055/11856/i/600/depositphotos_118565150-stock-photo-young-male-teacher.jpg",body:{role:"Doutora em Física Computacional - Universidade de São Paulo/São Carlos", classroom:"Instituto de Ciências Exatas e Biológicas - Sala 64", email:"andrea@iceb.ufop.br", lattes:"http://lattes.cnpq.br/0251364589832974", areaInterest:"Visão Computacional. Análise e processamento de imagens. Simulação computacional. Reconhecimento de padrões.", tel:"+55 (31) 3559 1640"}}, 
    {title:"Daniel Ludovico Guidoni",image:"https://st2.depositphotos.com/4431055/11856/i/600/depositphotos_118565150-stock-photo-young-male-teacher.jpg",body:{role:"Doutora em Física Computacional - Universidade de São Paulo/São Carlos", classroom:"Instituto de Ciências Exatas e Biológicas - Sala 64", email:"andrea@iceb.ufop.br", lattes:"http://lattes.cnpq.br/0251364589832974", areaInterest:"Visão Computacional. Análise e processamento de imagens. Simulação computacional. Reconhecimento de padrões.", tel:"+55 (31) 3559 1640"}},
    {title:"Dayanne Gouveia Coelho",image:"https://media.istockphoto.com/id/687830554/photo/portrait-of-a-happy-latin-american-teacher-at-the-school.jpg?b=1&s=170667a&w=0&k=20&c=uNKFMoebdWk1fMYsAQicTvDARuMVibx4pskppByrh5Q=",body:{role:"Doutora em Física Computacional - Universidade de São Paulo/São Carlos", classroom:"Instituto de Ciências Exatas e Biológicas - Sala 64", email:"andrea@iceb.ufop.br", lattes:"http://lattes.cnpq.br/0251364589832974", areaInterest:"Visão Computacional. Análise e processamento de imagens. Simulação computacional. Reconhecimento de padrões.", tel:"+55 (31) 3559 1640"}},
    {title:"Eduardo José da Silva Luz",image:"https://st2.depositphotos.com/4431055/11856/i/600/depositphotos_118565150-stock-photo-young-male-teacher.jpg",body:{role:"Doutora em Física Computacional - Universidade de São Paulo/São Carlos", classroom:"Instituto de Ciências Exatas e Biológicas - Sala 64", email:"andrea@iceb.ufop.br", lattes:"http://lattes.cnpq.br/0251364589832974", areaInterest:"Visão Computacional. Análise e processamento de imagens. Simulação computacional. Reconhecimento de padrões.", tel:"+55 (31) 3559 1640"}},
    {title:"Elton José da Silva",image:"https://st2.depositphotos.com/4431055/11856/i/600/depositphotos_118565150-stock-photo-young-male-teacher.jpg",body:{role:"Doutora em Física Computacional - Universidade de São Paulo/São Carlos", classroom:"Instituto de Ciências Exatas e Biológicas - Sala 64", email:"andrea@iceb.ufop.br", lattes:"http://lattes.cnpq.br/0251364589832974", areaInterest:"Visão Computacional. Análise e processamento de imagens. Simulação computacional. Reconhecimento de padrões.", tel:"+55 (31) 3559 1640"}},
    {title:"Fernanda Sumika Hojo de Souza",image:"https://media.istockphoto.com/id/687830554/photo/portrait-of-a-happy-latin-american-teacher-at-the-school.jpg?b=1&s=170667a&w=0&k=20&c=uNKFMoebdWk1fMYsAQicTvDARuMVibx4pskppByrh5Q=",body:{role:"Doutora em Física Computacional - Universidade de São Paulo/São Carlos", classroom:"Instituto de Ciências Exatas e Biológicas - Sala 64", email:"andrea@iceb.ufop.br", lattes:"http://lattes.cnpq.br/0251364589832974", areaInterest:"Visão Computacional. Análise e processamento de imagens. Simulação computacional. Reconhecimento de padrões.", tel:"+55 (31) 3559 1640"}},
    {title:"Fernando Cortez Sica",image:"https://st2.depositphotos.com/4431055/11856/i/600/depositphotos_118565150-stock-photo-young-male-teacher.jpg",body:{role:"Doutora em Física Computacional - Universidade de São Paulo/São Carlos", classroom:"Instituto de Ciências Exatas e Biológicas - Sala 64", email:"andrea@iceb.ufop.br", lattes:"http://lattes.cnpq.br/0251364589832974", areaInterest:"Visão Computacional. Análise e processamento de imagens. Simulação computacional. Reconhecimento de padrões.", tel:"+55 (31) 3559 1640"}},
    {title:"Gladston Juliano Prates Moreira",image:"https://st2.depositphotos.com/4431055/11856/i/600/depositphotos_118565150-stock-photo-young-male-teacher.jpg",body:{role:"Doutora em Física Computacional - Universidade de São Paulo/São Carlos", classroom:"Instituto de Ciências Exatas e Biológicas - Sala 64", email:"andrea@iceb.ufop.br", lattes:"http://lattes.cnpq.br/0251364589832974", areaInterest:"Visão Computacional. Análise e processamento de imagens. Simulação computacional. Reconhecimento de padrões.", tel:"+55 (31) 3559 1640"}},
    {title:"Guilherme Tavares de Assis",image:"https://st2.depositphotos.com/4431055/11856/i/600/depositphotos_118565150-stock-photo-young-male-teacher.jpg",body:{role:"Doutora em Física Computacional - Universidade de São Paulo/São Carlos", classroom:"Instituto de Ciências Exatas e Biológicas - Sala 64", email:"andrea@iceb.ufop.br", lattes:"http://lattes.cnpq.br/0251364589832974", areaInterest:"Visão Computacional. Análise e processamento de imagens. Simulação computacional. Reconhecimento de padrões.", tel:"+55 (31) 3559 1640"}},
    {title:"Guillermo Cámara Chávez",image:"https://st2.depositphotos.com/4431055/11856/i/600/depositphotos_118565150-stock-photo-young-male-teacher.jpg",body:{role:"Doutora em Física Computacional - Universidade de São Paulo/São Carlos", classroom:"Instituto de Ciências Exatas e Biológicas - Sala 64", email:"andrea@iceb.ufop.br", lattes:"http://lattes.cnpq.br/0251364589832974", areaInterest:"Visão Computacional. Análise e processamento de imagens. Simulação computacional. Reconhecimento de padrões.", tel:"+55 (31) 3559 1640"}},
    {title:"Gustavo Peixoto Silva",image:"https://st2.depositphotos.com/4431055/11856/i/600/depositphotos_118565150-stock-photo-young-male-teacher.jpg",body:{role:"Doutora em Física Computacional - Universidade de São Paulo/São Carlos", classroom:"Instituto de Ciências Exatas e Biológicas - Sala 64", email:"andrea@iceb.ufop.br", lattes:"http://lattes.cnpq.br/0251364589832974", areaInterest:"Visão Computacional. Análise e processamento de imagens. Simulação computacional. Reconhecimento de padrões.", tel:"+55 (31) 3559 1640"}},
    {title:"Jadson Castro Gertrudes",image:"https://st2.depositphotos.com/4431055/11856/i/600/depositphotos_118565150-stock-photo-young-male-teacher.jpg",body:{role:"Doutora em Física Computacional - Universidade de São Paulo/São Carlos", classroom:"Instituto de Ciências Exatas e Biológicas - Sala 64", email:"andrea@iceb.ufop.br", lattes:"http://lattes.cnpq.br/0251364589832974", areaInterest:"Visão Computacional. Análise e processamento de imagens. Simulação computacional. Reconhecimento de padrões.", tel:"+55 (31) 3559 1640"}},
    {title:"José Romildo Malaquias",image:"https://st2.depositphotos.com/4431055/11856/i/600/depositphotos_118565150-stock-photo-young-male-teacher.jpg",body:{role:"Doutora em Física Computacional - Universidade de São Paulo/São Carlos", classroom:"Instituto de Ciências Exatas e Biológicas - Sala 64", email:"andrea@iceb.ufop.br", lattes:"http://lattes.cnpq.br/0251364589832974", areaInterest:"Visão Computacional. Análise e processamento de imagens. Simulação computacional. Reconhecimento de padrões.", tel:"+55 (31) 3559 1640"}},
    {title:"Joubert de Castro Lima",image:"https://st2.depositphotos.com/4431055/11856/i/600/depositphotos_118565150-stock-photo-young-male-teacher.jpg",body:{role:"Doutora em Física Computacional - Universidade de São Paulo/São Carlos", classroom:"Instituto de Ciências Exatas e Biológicas - Sala 64", email:"andrea@iceb.ufop.br", lattes:"http://lattes.cnpq.br/0251364589832974", areaInterest:"Visão Computacional. Análise e processamento de imagens. Simulação computacional. Reconhecimento de padrões.", tel:"+55 (31) 3559 1640"}},
    {title:"Marcelo Luiz Silva",image:"https://st2.depositphotos.com/4431055/11856/i/600/depositphotos_118565150-stock-photo-young-male-teacher.jpg",body:{role:"Doutora em Física Computacional - Universidade de São Paulo/São Carlos", classroom:"Instituto de Ciências Exatas e Biológicas - Sala 64", email:"andrea@iceb.ufop.br", lattes:"http://lattes.cnpq.br/0251364589832974", areaInterest:"Visão Computacional. Análise e processamento de imagens. Simulação computacional. Reconhecimento de padrões.", tel:"+55 (31) 3559 1640"}},
    {title:"Marco Antonio Moreira de Carvalho",image:"https://st2.depositphotos.com/4431055/11856/i/600/depositphotos_118565150-stock-photo-young-male-teacher.jpg",body:{role:"Doutora em Física Computacional - Universidade de São Paulo/São Carlos", classroom:"Instituto de Ciências Exatas e Biológicas - Sala 64", email:"andrea@iceb.ufop.br", lattes:"http://lattes.cnpq.br/0251364589832974", areaInterest:"Visão Computacional. Análise e processamento de imagens. Simulação computacional. Reconhecimento de padrões.", tel:"+55 (31) 3559 1640"}},
    {title:"Pedro Henrique Lopes Silva",image:"https://st2.depositphotos.com/4431055/11856/i/600/depositphotos_118565150-stock-photo-young-male-teacher.jpg",body:{role:"Doutora em Física Computacional - Universidade de São Paulo/São Carlos", classroom:"Instituto de Ciências Exatas e Biológicas - Sala 64", email:"andrea@iceb.ufop.br", lattes:"http://lattes.cnpq.br/0251364589832974", areaInterest:"Visão Computacional. Análise e processamento de imagens. Simulação computacional. Reconhecimento de padrões.", tel:"+55 (31) 3559 1640"}},
    {title:"Puca Huachi Vaz Penna",image:"https://st2.depositphotos.com/4431055/11856/i/600/depositphotos_118565150-stock-photo-young-male-teacher.jpg",body:{role:"Doutora em Física Computacional - Universidade de São Paulo/São Carlos", classroom:"Instituto de Ciências Exatas e Biológicas - Sala 64", email:"andrea@iceb.ufop.br", lattes:"http://lattes.cnpq.br/0251364589832974", areaInterest:"Visão Computacional. Análise e processamento de imagens. Simulação computacional. Reconhecimento de padrões.", tel:"+55 (31) 3559 1640"}},
    {title:"Rafael Alves Bonfim de Queiroz",image:"https://st2.depositphotos.com/4431055/11856/i/600/depositphotos_118565150-stock-photo-young-male-teacher.jpg",body:{role:"Doutora em Física Computacional - Universidade de São Paulo/São Carlos", classroom:"Instituto de Ciências Exatas e Biológicas - Sala 64", email:"andrea@iceb.ufop.br", lattes:"http://lattes.cnpq.br/0251364589832974", areaInterest:"Visão Computacional. Análise e processamento de imagens. Simulação computacional. Reconhecimento de padrões.", tel:"+55 (31) 3559 1640"}},
    {title:"Reinaldo Silva Fortes",image:"https://st2.depositphotos.com/4431055/11856/i/600/depositphotos_118565150-stock-photo-young-male-teacher.jpg",body:{role:"Doutora em Física Computacional - Universidade de São Paulo/São Carlos", classroom:"Instituto de Ciências Exatas e Biológicas - Sala 64", email:"andrea@iceb.ufop.br", lattes:"http://lattes.cnpq.br/0251364589832974", areaInterest:"Visão Computacional. Análise e processamento de imagens. Simulação computacional. Reconhecimento de padrões.", tel:"+55 (31) 3559 1640"}},
    {title:"Ricardo Augusto Rabelo Oliveira",image:"https://st2.depositphotos.com/4431055/11856/i/600/depositphotos_118565150-stock-photo-young-male-teacher.jpg",body:{role:"Doutora em Física Computacional - Universidade de São Paulo/São Carlos", classroom:"Instituto de Ciências Exatas e Biológicas - Sala 64", email:"andrea@iceb.ufop.br", lattes:"http://lattes.cnpq.br/0251364589832974", areaInterest:"Visão Computacional. Análise e processamento de imagens. Simulação computacional. Reconhecimento de padrões.", tel:"+55 (31) 3559 1640"}},
    {title:"Rodrigo César Pedrosa Silva",image:"https://st2.depositphotos.com/4431055/11856/i/600/depositphotos_118565150-stock-photo-young-male-teacher.jpg",body:{role:"Doutora em Física Computacional - Universidade de São Paulo/São Carlos", classroom:"Instituto de Ciências Exatas e Biológicas - Sala 64", email:"andrea@iceb.ufop.br", lattes:"http://lattes.cnpq.br/0251364589832974", areaInterest:"Visão Computacional. Análise e processamento de imagens. Simulação computacional. Reconhecimento de padrões.", tel:"+55 (31) 3559 1640"}},
    {title:"Rodrigo Geraldo Ribeiro",image:"https://st2.depositphotos.com/4431055/11856/i/600/depositphotos_118565150-stock-photo-young-male-teacher.jpg",body:{role:"Doutora em Física Computacional - Universidade de São Paulo/São Carlos", classroom:"Instituto de Ciências Exatas e Biológicas - Sala 64", email:"andrea@iceb.ufop.br", lattes:"http://lattes.cnpq.br/0251364589832974", areaInterest:"Visão Computacional. Análise e processamento de imagens. Simulação computacional. Reconhecimento de padrões.", tel:"+55 (31) 3559 1640"}},
    {title:"Saul Emanuel Delabrida Silva",image:"https://st2.depositphotos.com/4431055/11856/i/600/depositphotos_118565150-stock-photo-young-male-teacher.jpg",body:{role:"Doutora em Física Computacional - Universidade de São Paulo/São Carlos", classroom:"Instituto de Ciências Exatas e Biológicas - Sala 64", email:"andrea@iceb.ufop.br", lattes:"http://lattes.cnpq.br/0251364589832974", areaInterest:"Visão Computacional. Análise e processamento de imagens. Simulação computacional. Reconhecimento de padrões.", tel:"+55 (31) 3559 1640"}},
    {title:"Tiago Garcia de Senna Carneiro",image:"https://st2.depositphotos.com/4431055/11856/i/600/depositphotos_118565150-stock-photo-young-male-teacher.jpg",body:{role:"Doutora em Física Computacional - Universidade de São Paulo/São Carlos", classroom:"Instituto de Ciências Exatas e Biológicas - Sala 64", email:"andrea@iceb.ufop.br", lattes:"http://lattes.cnpq.br/0251364589832974", areaInterest:"Visão Computacional. Análise e processamento de imagens. Simulação computacional. Reconhecimento de padrões.", tel:"+55 (31) 3559 1640"}},
    {title:"Túlio Ângelo Machado Toffolo",image:"https://st2.depositphotos.com/4431055/11856/i/600/depositphotos_118565150-stock-photo-young-male-teacher.jpg",body:{role:"Doutora em Física Computacional - Universidade de São Paulo/São Carlos", classroom:"Instituto de Ciências Exatas e Biológicas - Sala 64", email:"andrea@iceb.ufop.br", lattes:"http://lattes.cnpq.br/0251364589832974", areaInterest:"Visão Computacional. Análise e processamento de imagens. Simulação computacional. Reconhecimento de padrões.", tel:"+55 (31) 3559 1640"}},
    {title:"Valéria de Carvalho Santos",image:"https://media.istockphoto.com/id/687830554/photo/portrait-of-a-happy-latin-american-teacher-at-the-school.jpg?b=1&s=170667a&w=0&k=20&c=uNKFMoebdWk1fMYsAQicTvDARuMVibx4pskppByrh5Q=",body:{role:"Doutora em Física Computacional - Universidade de São Paulo/São Carlos", classroom:"Instituto de Ciências Exatas e Biológicas - Sala 64", email:"andrea@iceb.ufop.br", lattes:"http://lattes.cnpq.br/0251364589832974", areaInterest:"Visão Computacional. Análise e processamento de imagens. Simulação computacional. Reconhecimento de padrões.", tel:"+55 (31) 3559 1640"}},
    {title:"Vander Luis de Souza Freitas",image:"https://st2.depositphotos.com/4431055/11856/i/600/depositphotos_118565150-stock-photo-young-male-teacher.jpg",body:{role:"Doutora em Física Computacional - Universidade de São Paulo/São Carlos", classroom:"Instituto de Ciências Exatas e Biológicas - Sala 64", email:"andrea@iceb.ufop.br", lattes:"http://lattes.cnpq.br/0251364589832974", areaInterest:"Visão Computacional. Análise e processamento de imagens. Simulação computacional. Reconhecimento de padrões.", tel:"+55 (31) 3559 1640"}},
    {title:"Vinicius Antonio de Oliveira Martins",image:"https://st2.depositphotos.com/4431055/11856/i/600/depositphotos_118565150-stock-photo-young-male-teacher.jpg",body:{role:"Doutora em Física Computacional - Universidade de São Paulo/São Carlos", classroom:"Instituto de Ciências Exatas e Biológicas - Sala 64", email:"andrea@iceb.ufop.br", lattes:"http://lattes.cnpq.br/0251364589832974", areaInterest:"Visão Computacional. Análise e processamento de imagens. Simulação computacional. Reconhecimento de padrões.", tel:"+55 (31) 3559 1640"}}
];

const  employees = [
    {title:"Cristiano Amaro da Matta",image:"https://st2.depositphotos.com/4431055/11856/i/600/depositphotos_118565150-stock-photo-young-male-teacher.jpg", body:{role:"Técnico de Laboratório - Informática", classroom:"Instituto de Ciências Exatas e Biológicas - Sala COM 24 - ICEB I ",email:"decom@iceb.ufop.br",lattes:" ", areaInterest:" ", tel:"+55 (31) 3559-1692"}},
    {title:"Viviane Michelline Veloso Danese",image:"https://media.istockphoto.com/id/687830554/photo/portrait-of-a-happy-latin-american-teacher-at-the-school.jpg?b=1&s=170667a&w=0&k=20&c=uNKFMoebdWk1fMYsAQicTvDARuMVibx4pskppByrh5Q=",body:{role:"Secretária Executiva - DECOM", classroom:"Instituto de Ciências Exatas e Biológicas - Sala COM 24 - ICEB I",email:"decom@iceb.ufop.br",lattes:" ", areaInterest:" ", tel:"+55 (31) 3559-1692"}}
];

const  CACIC = [{title:"CACIC", image: "https://cacic.decom.ufop.br/sites/default/files/cacic/files/icone_0.png?m=1525724393", body:{role:"Centro Acadêmico Ciência da Computação_UFOP", classroom:"Instituto de Ciências Exatas e Biológicas - ICEB I ", email: "cacic.decom@gmail.com", lattes:" ", areaInterest:" ", tel:" "}}];

export default function People(){
    return (
        <>
        <Header />       
        <div><Tab
            title={"Pessoal"}
            tabs={[
                {name: "Discentes", content: discents},
                {name: "Funcionários", content: employees},
                {name: "CACIC", content: CACIC},
            ]}
        />
        </div>       
        <Footer/>
        </>
    );
}